'use client';
import { useEffect, useRef, useState } from 'react';
type Key='control'|'registers'|'alu'|'cache';
type Bridge={destroy:(x?:boolean)=>void;events:{emit:(e:string,...a:unknown[])=>void}};
const C:Record<Key,{name:string;short:string;role:string;clue:string;color:string}>={
 control:{name:'Control Unit',short:'CU',role:'Decodes instructions and directs the datapath.',clue:'I decode each instruction and tell the rest of the processor what to do.',color:'#ff7a59'},
 registers:{name:'Register File',short:'REG',role:'Stores the CPU’s fastest working values.',clue:'I hold the operands and results the CPU needs right now.',color:'#55d6be'},
 alu:{name:'Arithmetic Logic Unit',short:'ALU',role:'Performs arithmetic and logical operations.',clue:'I add, subtract, compare, and perform logical operations.',color:'#f7c948'},
 cache:{name:'L1 Cache',short:'L1',role:'Keeps frequently used data close to the CPU.',clue:'I keep recently used instructions and data nearby to reduce memory delays.',color:'#6da7ff'}};
const ORDER:Key[]=['control','registers','alu','cache'];
export default function CpuGame(){
 const host=useRef<HTMLDivElement>(null),bridge=useRef<Bridge|null>(null); const[score,setScore]=useState(1000),[step,setStep]=useState(0),[wrong,setWrong]=useState<Key|null>(null),[feedback,setFeedback]=useState('Read the highlighted socket, then choose the component that matches its job.'); const current=ORDER[step],complete=step===4;
 useEffect(()=>{if(!host.current)return;let game:Bridge|undefined,active=true;import('phaser').then(P=>{if(!active||!host.current)return;const slots=[{key:'control' as Key,x:460,y:130},{key:'registers' as Key,x:270,y:300},{key:'alu' as Key,x:650,y:300},{key:'cache' as Key,x:460,y:455}];class Scene extends P.Scene{boxes=new Map<Key,any>();titles=new Map<Key,any>();activeKey:Key=ORDER[0];create(){this.cameras.main.setBackgroundColor('#08111f');const g=this.add.graphics();g.fillStyle(0x0d1b2d,1).fillRoundedRect(62,35,796,490,28);g.lineStyle(2,0x29425f,1).strokeRoundedRect(62,35,796,490,28);g.lineStyle(5,0x17304b,.95);g.lineBetween(460,184,460,401);g.lineBetween(405,300,515,300);g.lineBetween(460,184,320,246);g.lineBetween(460,184,600,246);g.lineBetween(320,354,460,401);g.lineBetween(600,354,460,401);this.add.text(92,58,'PROCESSOR DIE / GUIDED ASSEMBLY',{fontFamily:'monospace',fontSize:'13px',color:'#6f8fad',letterSpacing:2});slots.forEach((s,i)=>{const b=this.add.rectangle(s.x,s.y,270,108,0x111f33).setStrokeStyle(2,0x3b5775);this.add.text(s.x-116,s.y-39,`0${i+1}`,{fontFamily:'monospace',fontSize:'10px',color:'#6f8fad'});const t=this.add.text(s.x,s.y-25,i?'LOCKED':'ACTIVE SOCKET',{fontFamily:'monospace',fontSize:'11px',fontStyle:'bold',color:i?'#496783':'#f7c948'}).setOrigin(.5);this.add.text(s.x,s.y+16,C[s.key].clue,{fontFamily:'Arial',fontSize:'12px',color:'#9fb2c4',align:'center',wordWrap:{width:226}}).setOrigin(.5);this.boxes.set(s.key,b);this.titles.set(s.key,t)});this.paint(ORDER[0]);this.game.events.on('correct',(key:Key,next?:Key)=>{this.boxes.get(key)?.setFillStyle(P.Display.Color.HexStringToColor(C[key].color).color,.95).setStrokeStyle(2,0xffffff,.2);this.titles.get(key)?.setText(`✓ ${C[key].name.toUpperCase()}`).setColor('#07101c');if(next)this.paint(next);else this.cameras.main.flash(500,85,214,190,false)});this.game.events.on('wrong',()=>{const b=this.boxes.get(this.activeKey);this.tweens.add({targets:b,x:'+=8',yoyo:true,repeat:3,duration:45});this.cameras.main.flash(120,255,80,70,false)})}paint(k:Key){this.activeKey=k;this.boxes.get(k)?.setStrokeStyle(4,0xf7c948).setFillStyle(0x172a40);this.titles.get(k)?.setText('ACTIVE SOCKET').setColor('#f7c948')}}game=new P.Game({type:P.AUTO,parent:host.current,width:920,height:560,scene:Scene,scale:{mode:P.Scale.FIT,autoCenter:P.Scale.CENTER_BOTH}}) as Bridge;bridge.current=game});return()=>{active=false;game?.destroy(true);bridge.current=null}},[]);
 function choose(k:Key){if(!current)return;if(k===current){const n=step+1;setScore(v=>v+250);setStep(n);setWrong(null);setFeedback(`${C[k].name} installed correctly. ${C[k].role}`);bridge.current?.events.emit('correct',k,ORDER[n])}else{setScore(v=>Math.max(0,v-100));setWrong(k);setFeedback(`Incorrect: ${C[k].name} ${C[k].role.toLowerCase()} Re-read the socket and try again. −100 points.`);bridge.current?.events.emit('wrong')}}
 return <main className="game-shell"><header className="topbar"><div className="brand"><span className="brand-mark">μ</span><div><b>CPU ARCHITECT</b><span>BUILD • CONNECT • EXECUTE</span></div></div><div className="mission"><span>MISSION 01</span><b>Assemble the Core</b></div><div className="score"><span>SCORE</span><b>{score.toString().padStart(4,'0')}</b></div></header><section className="workbench guided"><aside className="intel-panel"><span className="eyebrow">INSTALLATION {Math.min(step+1,4)} OF 4</span><h1>{complete?'Core online.':'Identify the component.'}</h1><p>{complete?'Every component is installed. The simplified processor is ready to execute instructions.':'Read the function shown in the highlighted socket. Choose the one CPU component that performs that job.'}</p>{!complete?<div className="choices" role="group">{ORDER.map(k=><button key={k} className={wrong===k?'wrong':''} onClick={()=>choose(k)}><span style={{background:C[k].color}}>{C[k].short}</span><b>{C[k].name}</b><small>SELECT</small></button>)}</div>:<div className="completion-card"><b>MISSION COMPLETE</b><span>Final score: {score}</span><button onClick={()=>location.reload()}>REBUILD CORE</button></div>}<div className="progress-label"><span>CORE COMPLETION</span><b>{step}/4</b></div><div className="progress"><i style={{width:`${step*25}%`}}/></div></aside><section className="game-panel"><div ref={host} className="phaser-host"/><div className={`feedback ${complete?'complete':wrong?'error':''}`} aria-live="polite"><span>{complete?'CORE ONLINE':wrong?'POINT PENALTY':'ARCHITECT LOG'}</span><p>{feedback}</p></div></section></section><footer><span>CSC 3501 • COMPUTER ORGANIZATION & DESIGN</span><span>PHASER.JS PROTOTYPE</span></footer></main>}
